print(" Veuillez entrez une valeur x ")
x = int(input())
print(" Veuillez entrez une valeur y ")
y = int(input())
print(" avant permutation : x : ", x, "y: ", y)
print(" après permutation : x : ", y, "y: ", x)
